### ISSUE TITLE
React Tooltip component throws "out of scope" exception

### ISSUE THREAD

**Issue by SSopin** [Milkdown/examples#3]
Hi,

I copied the code from React Tooltip example into my app and it breaks the editor when tries to execute the following: 
```
        ctx.set(tooltip.key, {
          view: pluginViewFactory({
            component: TooltipView,
          })
        })
```

Here is the error: 
```
Error: out of scope
    at pluginViewContext.ts:23:1
    at ModelDescriptionEditor.tsx:35:1
    at editor.ts:76:1
    at Array.map (<anonymous>)
    at editor.ts:76:1
    at config.ts:15:1
    at editor.ts:143:1
    at Array.map (<anonymous>)
    at ve.<anonymous> (editor.ts:133:1)
    at ve.create (editor.ts:210:1)
```

Am I doing something wrong? I didn't even change the code, just copied it.

**Comment by JorgeAtPaladin** [comment]
+1 we have the same.

**Comment by Saul-Mirone** [comment]
You'll need to add `linkTooltipPlugin` to your plugin list. Check this line:
https://github.com/Milkdown/examples/blob/main/component-link-tooltip/src/main.ts#L56
